version: '3'

services:
    brevets:
        build: brevets/.
        ports: 
          - "5001:5000"
        depends_on:
            - mymongodb
        environment:
            MONGODB_HOSTNAME: mymongodb
        command: python flask_brevets.py
    mymongodb:
        image: mongo:5.0.5
      # ports:
      #     - "5001:27017"
